# Generated by Django 5.0.3 on 2024-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('CNIC', models.CharField(max_length=14, unique=True)),
                ('phone', models.CharField(max_length=13, unique=True)),
            ],
        ),
    ]
