# Generated by Django 5.0.2 on 2024-03-28 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.banks'),
        ),
    ]
