# Generated by Django 5.0.2 on 2024-03-28 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_accounts_bank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='bank_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.banks'),
        ),
    ]
