# Generated by Django 5.0.3 on 2024-05-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_beneficiary_userbeneficiaryrelationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="bank",
            field=models.ForeignKey(
                default=11, on_delete=django.db.models.deletion.CASCADE, to="app.banks"
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="user",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="beneficiary",
            name="account_number",
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
