# Generated by Django 5.0.3 on 2024-05-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_mobiletopup"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_number", models.CharField(max_length=13)),
                ("network_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="mobiletopup",
            name="user",
        ),
    ]
