# Generated by Django 5.0.3 on 2024-05-08 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_mobilenumber_network_remove_mobiletopup_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobilenumber",
            name="network_id",
        ),
        migrations.RemoveField(
            model_name="mobiletopup",
            name="network",
        ),
        migrations.AddField(
            model_name="mobilenumber",
            name="network",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="app.network"
            ),
        ),
        migrations.AddField(
            model_name="mobiletopup",
            name="user",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
        migrations.AlterField(
            model_name="mobiletopup",
            name="mobile_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.mobilenumber"
            ),
        ),
    ]
