# Generated by Django 5.0.3 on 2024-05-08 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_rename_network_mobilenumber_network_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobiletopup",
            old_name="user",
            new_name="user_id",
        ),
    ]
