# Generated by Django 5.0.3 on 2024-05-08 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_rename_user_mobiletopup_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobiletopup",
            name="amount",
        ),
    ]
