# Generated by Django 5.0.3 on 2024-05-08 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_remove_mobiletopup_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilenumber",
            old_name="network_id",
            new_name="network",
        ),
        migrations.RenameField(
            model_name="mobiletopup",
            old_name="mobile_number_id",
            new_name="mobile_number",
        ),
        migrations.RenameField(
            model_name="mobiletopup",
            old_name="user_id",
            new_name="user",
        ),
    ]
