# Generated by Django 5.0.3 on 2024-05-08 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_rename_network_id_mobilenumber_network_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilenumber",
            name="network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.network"
            ),
        ),
        migrations.AlterField(
            model_name="mobiletopup",
            name="mobile_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.mobilenumber"
            ),
        ),
        migrations.AlterField(
            model_name="mobiletopup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
    ]
