# Generated by Django 5.0.3 on 2024-05-11 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_billcompany_billcustomer_userbill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billcustomer",
            old_name="name",
            new_name="bill_number",
        ),
    ]
