# Generated by Django 5.0.3 on 2024-05-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_billcompany_billcustomer_userbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='account_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
